//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compositeprimarykey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPO
    {
        public int EMP_ID { get; set; }
        public int DEPT_ID { get; set; }
        public string EMPNAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> SALARY { get; set; }
    }
}
